(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},ca=ba(this),da=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var e=0;e<
a.length-1;e++){var g=a[e];if(!(g in c))break a;c=c[g]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}},ea="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},d;
if("function"==typeof Object.setPrototypeOf)d=Object.setPrototypeOf;else{var l;a:{var fa={a:!0},m={};try{m.__proto__=fa;l=m.a;break a}catch(a){}l=!1}d=l?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var n=d;
da("Array.from",function(a){return a?a:function(b,c,e){c=null!=c?c:function(k){return k};var g=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var h=0;!(f=b.next()).done;)g.push(c.call(e,f.value,h++))}else for(f=b.length,h=0;h<f;h++)g.push(c.call(e,b[h],h));return g}});var p=this||self,q=function(a){return a};var ha=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,e="string"===typeof a?a.split(""):a,g=0;g<c;g++)if(g in e&&b.call(void 0,e[g],g,a))return!0;return!1};var r,t=function(){if(void 0===r){var a=null,b=p.trustedTypes;if(b&&b.createPolicy){try{a=b.createPolicy("goog#html",{createHTML:q,createScript:q,createScriptURL:q})}catch(c){p.console&&p.console.error(c.message)}r=a}else r=a}return r};var v=function(a,b){this.g=b===u?a:""};v.prototype.toString=function(){return this.g+""};var u={};var w;a:{var x=p.navigator;if(x){var y=x.userAgent;if(y){w=y;break a}}w=""};var A=function(a,b,c){this.g=c===z?a:""};A.prototype.toString=function(){return this.g.toString()};var z={};var ia={},D=null;var ja="function"===typeof Uint8Array;var E=function(){},F,ka=Object.freeze([]),la=function(a){var b=a.j+a.h;a.g[b]||(a.i=a.g[b]={})},G=function(a,b,c){b<a.j?a.g[b+a.h]=c:(la(a),a.i[b]=c);return a},H=function(a){if(a.l)for(var b in a.l){var c=a.l[b];if(Array.isArray(c))for(var e=0;e<c.length;e++)c[e]&&H(c[e]);else c&&H(c)}return a.g};
E.prototype.s=ja?function(){var a=Uint8Array.prototype.toJSON;Uint8Array.prototype.toJSON=function(){var b;void 0===b&&(b=0);if(!D){D={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),e=["+/=","+/","-_=","-_.","-_"],g=0;5>g;g++){var f=c.concat(e[g].split(""));ia[g]=f;for(var h=0;h<f.length;h++){var k=f[h];void 0===D[k]&&(D[k]=h)}}}b=ia[b];c=Array(Math.floor(this.length/3));e=b[64]||"";for(g=f=0;f<this.length-2;f+=3){var B=this[f],C=this[f+1];k=this[f+2];h=b[B>>
2];B=b[(B&3)<<4|C>>4];C=b[(C&15)<<2|k>>6];k=b[k&63];c[g++]=h+B+C+k}h=0;k=e;switch(this.length-f){case 2:h=this[f+1],k=b[(h&15)<<2]||e;case 1:f=this[f],c[g]=b[f>>2]+b[(f&3)<<4|h>>4]+k+e}return c.join("")};try{return JSON.stringify(this.g&&H(this),ma)}finally{Uint8Array.prototype.toJSON=a}}:function(){return JSON.stringify(this.g&&H(this),ma)};var ma=function(a,b){return"number"!==typeof b||!isNaN(b)&&Infinity!==b&&-Infinity!==b?b:String(b)};E.prototype.toString=function(){return H(this).toString()};var I=function(a){var b=a;a=na;this.l=null;F&&(b||(b=F),F=null);var c=this.constructor.H,e=this.constructor.G;e=c||e;b||(b=e?[c]:[]);this.h=e?0:-1;this.g=b;a:{if(b=this.g.length)if(--b,c=this.g[b],!(null===c||"object"!=typeof c||Array.isArray(c)||ja&&c instanceof Uint8Array)){this.j=b-this.h;this.i=c;break a}this.j=Number.MAX_VALUE}if(a)for(b=0;b<a.length;b++)c=a[b],c<this.j?(c+=this.h,this.g[c]=this.g[c]||ka):(la(this),this.i[c]=this.i[c]||ka)};I.prototype=ea(E.prototype);
I.prototype.constructor=I;if(n)n(I,E);else for(var J in E)if("prototype"!=J)if(Object.defineProperties){var oa=Object.getOwnPropertyDescriptor(E,J);oa&&Object.defineProperty(I,J,oa)}else I[J]=E[J];var na=[6];var ra=function(a,b){if(!pa()){var c=Math.random();if(c<b)return c=qa(),a[Math.floor(c*a.length)]}return null},qa=function(){if(!p.crypto)return Math.random();try{var a=new Uint32Array(1);p.crypto.getRandomValues(a);return a[0]/65536/65536}catch(b){return Math.random()}},pa=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){return ha(["Google Web Preview","Mediapartners-Google","Google-Read-Aloud","Google-Adwords"],sa)||1E-4>Math.random()}),sa=function(a){return-1!=w.indexOf(a)};var ta=["platform","platformVersion","architecture","model","uaFullVersion"],ua=function(){return p.navigator&&p.navigator.userAgentData&&"function"===typeof p.navigator.userAgentData.getHighEntropyValues?p.navigator.userAgentData.getHighEntropyValues(ta).then(function(a){var b=new I;b=G(b,1,a.platform);b=G(b,2,a.platformVersion);b=G(b,3,a.architecture);b=G(b,4,a.model);return G(b,5,a.uaFullVersion)}):null};var va=function(a,b){b=void 0===b?!0:b;try{for(var c=null;c!=a;c=a,a=a.parent)switch(a.location.protocol){case "https:":return!0;case "file:":return b;case "http:":return!1}}catch(e){}return!0}(p,!1)?"https:":"http:";var wa={F:1,v:4,A:5,u:7,B:9,C:10,D:11},K={o:"40004006",m:"40004007"};function xa(){return{1:.5,4:.02,5:.001,7:.5,9:.05,10:.2,11:0}}function ya(){var a=za,b=typeof a;if(("object"!=b||null==a)&&"function"!=b)return!1;for(var c in wa)if(b=a[wa[c]],"number"!==typeof b||0>b||1<b)return!1;return!0};function Aa(){var a=p.dcmads;if(null!=a.eids)return a.eids;var b=p.navigator;return b.connection&&b.connection.saveData?(a=ra([K.o,K.m],a.expts[4]))?"4|"+a:"":""}function Ba(){if(!p.dcmads.uach){var a=ua();a&&a.then(function(b){p.dcmads.uach=b.s()})}};try{p.dcmads=p.dcmads||{};p.dcmads.startTime=(new Date).getTime();var Ca=p.dcmads,L=p.dcmads.version,M={loader:217};if(L)if(M.experiment=L.experiment,75==L.number||"p"==L.number)M.number=75;else if(75==L.number||"c"==L.number)M.number=75;if(!M.number){var Da=ra([75,75],0);M.experiment=!!Da;M.number=Da||75}Ca.version=M;var Ea=p.dcmads,Fa,za=p.dcmads.expts,N;N=void 0===N?xa:N;Fa=ya()?za:N();Ea.expts=Fa;p.dcmads.eids=Aa();Ba();var Ga="4|"+K.m,Ha=p.dcmads.version,Ia=Ha.number,Ja="";Ha.experiment&&75==
Ia&&(Ja="?rxp=75x75");var Ka="impl_v"+Ia+".js"+Ja,La=p.document,Ma=La.currentScript||Array.from(La.getElementsByTagName("script")).pop(),O=(0==(Ma&&Ma.src||"").indexOf("http:")?"http:":"https:")+"//www.googletagservices.com/dcm/"+Ka;if(p.dcmads.eids===Ga){var Na=p.document,Oa=t(),Pa=Oa?Oa.createScriptURL(O):O,P=Na.createElement("script"),Q=new v(Pa,u);P.src=Q instanceof v&&Q.constructor===v?Q.g:"type_error:TrustedResourceUrl";var Qa,R,Ra=(P.ownerDocument&&P.ownerDocument.defaultView||window).document,
S=null===(R=Ra.querySelector)||void 0===R?void 0:R.call(Ra,"script[nonce]");(Qa=S?S.nonce||S.getAttribute("nonce")||"":"")&&P.setAttribute("nonce",Qa);var T=Na.getElementsByTagName("script")[0];T&&T.parentNode&&T.parentNode.insertBefore(P,T)}else{var Sa=p.document,U,Ta='<script src="'+O+'">\x3c/script>',Ua=t(),Va=Ua?Ua.createHTML(Ta):Ta;U=new A(Va,null,z);Sa.write(U instanceof A&&U.constructor===A?U.g:"type_error:SafeHtml")}}catch(a){if(.01>Math.random()){var V="";try{var W,X=a.toString();a.name&&
-1==X.indexOf(a.name)&&(X+=": "+a.name);a.message&&-1==X.indexOf(a.message)&&(X+=": "+a.message);if(a.stack){var Y=a.stack,Z=X;try{-1==Y.indexOf(Z)&&(Y=Z+"\n"+Y);for(var Wa;Y!=Wa;)Wa=Y,Y=Y.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");X=Y.replace(/\n */g,"\n")}catch(b){X=Z}}W=X;W=W.substring(0,1024);V=encodeURIComponent(W)}catch(b){V="extr"}var Xa=p.dcmads.eids,Ya=document.createElement("img");Ya.src=va+"//pagead2.googlesyndication.com/pagead/gen_204?id=dcmads-err&ver=217&context=554"+
((Xa?"&eids="+Xa:"")+"&msg="+V);(p.google_image_requests=p.google_image_requests||[]).push(Ya)}};}).call(this);
